wip debug

diff --git a/.github/workflows/package_core.yml b/.github/workflows/package_core.yml
--- a/.github/workflows/package_core.yml
+++ b/.github/workflows/package_core.yml
@@ -5,341 +5,19 @@ on:
   - pull_request
 
 jobs:
-  build-env:
-    name: Prepare build environment
-    runs-on: ubuntu-latest
-    outputs:
-      CORE_TAG: ${{ env.CORE_TAG }}
-      CORE_HASH: ${{ env.CORE_HASH }}
-      ALL_BOARD_DATA: ${{ env.ALL_BOARD_DATA }}
-      ARTIFACTS: ${{ env.ARTIFACTS }}
-      SUB_ARCHES: ${{ env.SUB_ARCHES }}
-    steps:
-
-      - name: Install OS dependencies
-        working-directory: /opt
-        run: |
-          sudo apt-get remove --purge man-db -y # skips the mandb triggers
-          sudo apt-get update
-          sudo apt-get install -y --no-install-recommends git cmake wget python3-pip ninja-build
-
-      - uses: actions/checkout@v4
-        with:
-          submodules: 'recursive'
-          fetch-depth: 0
-          persist-credentials: false
-          fetch-tags: true
-
-      - name: Initialize Zephyr environment
-        run: |
-          yes | ./extra/bootstrap.sh -o=--filter=tree:0
-          echo "CORE_HASH=$(git describe --always)" >> "$GITHUB_ENV"
-          echo "ALL_BOARD_DATA=$(extra/get_board_details.sh | jq -c 'sort_by(.variant)')" >> "$GITHUB_ENV"
-          echo "## Building \`$(extra/get_core_version.sh)\`" >> "$GITHUB_STEP_SUMMARY"
-
-      - name: Map output packages
-        # needs the above env vars to be usable
-        run: |
-          echo "CORE_TAG=$(git describe --tags --exact-match 2>/dev/null || echo $CORE_HASH)" >> "$GITHUB_ENV"
-          echo "ARTIFACTS=$(jq -c '["zephyr"] + (map(.artifact) | unique)' <<< ${ALL_BOARD_DATA})" >> "$GITHUB_ENV"
-          echo "SUB_ARCHES=$(jq -c 'map(.subarch) | unique' <<< ${ALL_BOARD_DATA})" >> "$GITHUB_ENV"
-
-          (cd && tar cphf - .cmake work zephyr-sdk-* | zstd > build-env.tar.zstd)
-          tar cphf - cores/arduino/api | zstd > arduino-api.tar.zstd
-
-      - name: Archive build environment
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-env
-          path: ~/build-env.tar.zstd
-
-      - name: Archive API snapshot
-        uses: actions/upload-artifact@v4
-        with:
-          name: arduino-api
-          path: arduino-api.tar.zstd
-
-  build-board:
-    name: Build loader for ${{ matrix.board }}
-    runs-on: ubuntu-latest
-    needs:
-      - build-env
-    env:
-      CCACHE_IGNOREOPTIONS: -specs=*
-      ARTIFACT_TAG: ${{ needs.build-env.outputs.CORE_HASH }}-${{ matrix.board }}
-    strategy:
-      matrix:
-        include:
-          ${{ fromJSON( needs.build-env.outputs.ALL_BOARD_DATA ) }}
-      fail-fast: false
-    steps:
-      - uses: actions/download-artifact@v4
-        with:
-          path: /home/runner
-          name: build-env
-
-      - name: Restore build environment
-        run: |
-          sudo apt-get remove --purge man-db -y # skips the mandb triggers
-          sudo apt-get update
-          sudo apt-get install -y --no-install-recommends git cmake wget python3-pip ninja-build ccache
-          (cd ~ && tar --use-compress-program=unzstd -xpf build-env.tar.zstd && rm build-env.tar.zstd)
-
-      - name: ccache
-        uses: hendrikmuhs/ccache-action@v1.2
-        with:
-          verbose: 1
-          key: ${{ github.job }}-${{ matrix.board }} 
-
-      - name: Build loader
-        shell: bash
-        run: |
-          REPORT=reports/zephyr-${{ matrix.variant }}
-          mkdir -p reports
-          if ! ./extra/build.sh ${{ matrix.board }} 1> >(tee $REPORT.stdout) 2> >(tee $REPORT.stderr) ; then
-            echo "### :x: ${{ matrix.board }} (\`${{ matrix.variant }}\`) build errors" > $GITHUB_STEP_SUMMARY
-            echo >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            cat $REPORT.stderr >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-
-          # look for warnings (errors are a happy path!)
-          grep -i "warning:" $REPORT.stdout > $REPORT.warnings || true
-
-          # extract the memory usage table (from the header to the first non-% line)
-          cat $REPORT.stdout | sed -n '/^Memory region/,/^[^%]*$/p' | head -n -1 \
-                             | awk 'BEGIN {split("B KB MB GB", u); for(i in u) m[u[i]]=1024^(i-1)} /:/ {print "[\"" $1 "\"," $2*m[$3] "," $4*m[$5] "]"}' \
-                             | sort | jq -s > $REPORT.meminfo
-
-      - name: Get build job ID
-        id: job_id
-        if: ${{ success() || failure() }}
-        uses: actions/github-script@main
-        with:
-          script: |
-            const { data: workflow_run } = await github.rest.actions.listJobsForWorkflowRun({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: context.runId
-            });
-            const job_name = `Build loader for ${{ matrix.board }}`
-            return workflow_run.jobs.find((job) => job.name === job_name).id;
-
-      - name: Package board artifacts
-        if: ${{ !cancelled() }}
-        run: |
-          # Add job ID report
-          echo ${{ steps.job_id.outputs.result }} > $REPORT.jobid
-          echo "REPORT_FILES<<EOF" >> $GITHUB_ENV
-          ls reports/* >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-
-          # Archive built binaries (and build dir on failure)
-          [ "${{ job.status }}" == "failure" ] && FULL_BUILD_DIR="build/${{ matrix.variant }}/"
-          tar chf - \
-            firmwares/*${{ matrix.variant }}* \
-            variants/${{ matrix.variant }}/ \
-            ${FULL_BUILD_DIR} \
-          | zstd > binaries-${ARTIFACT_TAG}.tar.zstd
-
-      - name: Archive board binaries
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ format('{0}binaries-{1}', (job.status == 'failure') && 'failed-' || '', env.ARTIFACT_TAG) }}
-          path: binaries-${{ env.ARTIFACT_TAG }}.tar.zstd
-
-      - name: Archive build reports
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-report-${{ env.ARTIFACT_TAG }}
-          path: ${{ env.REPORT_FILES }}
-
-  package-core:
-    name: Package ${{ matrix.artifact }}
-    runs-on: ubuntu-latest
-    needs:
-      - build-env
-      - build-board
-    env:
-      ALL_BOARD_DATA: ${{ needs.build-env.outputs.ALL_BOARD_DATA }}
-      CORE_ARTIFACT: ArduinoCore-${{ matrix.artifact }}-${{ needs.build-env.outputs.CORE_HASH }}
-      CORE_TAG: ${{ needs.build-env.outputs.CORE_TAG }}
-    strategy:
-      matrix:
-        artifact: ${{ fromJSON( needs.build-env.outputs.ARTIFACTS ) }}
-      fail-fast: false
-    if: ${{ !cancelled() && needs.build-env.result == 'success' }}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: 'recursive'
-          fetch-depth: 0
-          persist-credentials: false
-          fetch-tags: true
-
-      - uses: actions/download-artifact@v4
-        with:
-          path: .
-          name: arduino-api
-
-      - uses: actions/download-artifact@v4
-        with:
-          path: .
-          pattern: binaries-*
-          merge-multiple: true
-
-      - name: Package core
-        run: |
-          rm -f cores/arduino/api # remove broken symlink
-          tar --use-compress-program=unzstd -xpf arduino-api.tar.zstd
-          for f in binaries-*.tar.zstd ; do
-            tar --use-compress-program=unzstd -xpf $f
-          done
-          ./extra/package_core.sh ${{ matrix.artifact }} ${CORE_TAG} distrib/${CORE_ARTIFACT}.tar.bz2
-
-      - uses: actions/upload-artifact@v4
-        if: ${{ success() || failure() }}
-        with:
-          name: ${{ env.CORE_ARTIFACT }}
-          path: distrib/${{ env.CORE_ARTIFACT }}.tar.bz2
-
-  cleanup-build:
-    name: Clean up intermediates
-    runs-on: ubuntu-latest
-    needs:
-      - package-core
-    steps:
-      - uses: geekyeggo/delete-artifact@v5.1.0
-        with:
-          name: |
-            arduino-api
-            binaries-*
-            build-env
-          failOnError: false
-
-  test-core:
-    name: Test ${{ matrix.subarch }}:${{ matrix.board }}
-    runs-on: ubuntu-latest
-    needs:
-      - build-env
-      - package-core
-    strategy:
-      matrix:
-        include:
-          ${{ fromJSON( needs.build-env.outputs.ALL_BOARD_DATA ) }}
-      fail-fast: false
-    env:
-      PLAT: arduino:${{ matrix.subarch }}
-      FQBN: arduino:${{ matrix.subarch }}:${{ matrix.board }}
-      CORE_ARTIFACT: ArduinoCore-${{ matrix.artifact }}-${{ needs.build-env.outputs.CORE_HASH }}
-      ARTIFACT_TAG: ${{ needs.build-env.outputs.CORE_HASH }}-${{ matrix.board }}
-    if: ${{ !cancelled() && needs.build-env.result == 'success' }}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          sparse-checkout: |
-            extra/ci_test_list.sh
-            extra/artifacts/
-
-      - uses: actions/download-artifact@v4
-        with:
-          name: ${{ env.CORE_ARTIFACT }}
-
-      - name: Set up core
-        run: |
-          tar xf ${CORE_ARTIFACT}.tar.bz2 # will create ArduinoCore-zephyr/
-          echo "REPORT_FILE=$(echo ${FQBN} | tr ':' '-').json" >> $GITHUB_ENV
-
-      - name: Get test sketches
-        run: |
-          # sets ALL_TESTS and ALL_LIBRARIES env vars
-          extra/ci_test_list.sh ${{ matrix.artifact }} ${{ matrix.variant }}
-
-      - name: Compile tests for ${{ matrix.board }}
-        uses: pillo79/compile-sketches@next
-        with:
-          fqbn: ${{ env.FQBN }}
-          platforms: |
-            # Use Board Manager version first, to install the toolchain
-            - name: ${{ env.PLAT }}
-            - name: ${{ env.PLAT }}
-              source-path: "ArduinoCore-zephyr"
-          sketch-paths: |
-            ${{ env.ALL_TESTS }}
-          libraries: |
-            ${{ env.ALL_LIBRARIES }}
-          cli-compile-flags: |
-            - '--build-property'
-            - 'compiler.c.extra_flags=-Wno-type-limits -Wno-missing-field-initializers'
-            - '--build-property'
-            - 'compiler.cpp.extra_flags=-Wno-type-limits -Wno-missing-field-initializers'
-          verbose: 'false'
-          enable-deltas-report: 'false'
-          enable-issues-report: 'true'
-          always-succeed: 'true'
-
-      - name: Get test job ID
-        id: job_id
-        if: ${{ success() || failure() }}
-        uses: actions/github-script@main
-        with:
-          script: |
-            const { data: workflow_run } = await github.rest.actions.listJobsForWorkflowRun({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: context.runId
-            });
-            const job_name = `Test ${{ matrix.subarch }}:${{ matrix.board }}`
-            return workflow_run.jobs.find((job) => job.name === job_name).id;
-
-      - name: Prepare log
-        if: ${{ success() || failure() }}
-        run: |
-          [ ! -f sketches-reports/${REPORT_FILE} ] && mkdir -p sketches-reports && echo "{}" > sketches-reports/${REPORT_FILE}
-          sed -i -e 's!/home/runner/.arduino15/packages/arduino/hardware/zephyr/[^/]*/!!g' sketches-reports/${REPORT_FILE}
-          cat sketches-reports/${REPORT_FILE} | jq -cr ". += { job_id: ${{ steps.job_id.outputs.result }} }" > ${REPORT_FILE} && mv ${REPORT_FILE} sketches-reports/
-
-      - uses: actions/upload-artifact@v4
-        if: ${{ success() || failure() }}
-        with:
-          name: test-report-${{ env.ARTIFACT_TAG }}
-          path: sketches-reports/*
-
   inspect-logs:
     name: Analyze logs
     runs-on: ubuntu-latest
-    needs:
-      - build-env
-      - package-core
-      - test-core
-    if: ${{ !cancelled() && needs.build-env.result == 'success' }}
-    env:
-      ALL_BOARD_DATA: ${{ needs.build-env.outputs.ALL_BOARD_DATA }}
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-
-      - uses: actions/download-artifact@v4
-        with:
-          path: .
-          pattern: "*-report-*"
-          merge-multiple: true
-
       # Collect and summarize logs
       - run: |
           mkdir -p reports
+
           echo ${{ github.event.pull_request.number }} > pr_number
-          extra/ci_inspect_logs.py reports/result reports/summary reports/full_log
-          echo "CI_RESULT=$(cat reports/result)" > $GITHUB_OUTPUT
-          if ${{ github.event_name != 'pull_request' && 'true' || 'false' }}; then
+          echo "CI_RESULT=PASSED" > $GITHUB_OUTPUT
+          echo "summary text" > reports/summary
+          echo "full log" > reports/full_log
+          if [ "${{ github.event_name }}" != "pull_request" ]; then
             cat reports/summary >> $GITHUB_STEP_SUMMARY
           fi
           cat reports/full_log >> $GITHUB_STEP_SUMMARY
@@ -361,80 +39,9 @@ jobs:
   verify-core:
     runs-on: ubuntu-latest
     needs:
-      - build-env
-      - package-core
       - inspect-logs
     if: ${{ !cancelled() }}
     steps:
       - name: CI run result
         run: |
-          exit ${{ ((needs.inspect-logs.CI_RESULT == 'PASSED') && !contains(needs.*.result, 'failure')) && '0' || '1' }}
-
-  publish-core:
-    name: Publish core
-    runs-on: ubuntu-latest
-    if: ${{ github.event_name == 'push' && github.repository == 'arduino/ArduinoCore-zephyr' }}
-    needs:
-      - build-env
-      - package-core
-      - inspect-logs
-    environment: production
-    permissions:
-      id-token: write
-      contents: read
-    steps:
-      - uses: actions/download-artifact@v4
-        with:
-          path: .
-          pattern: ArduinoCore-*
-          merge-multiple: true
-
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.IAM_ROLE }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Upload artifact
-        run: |
-          for f in ArduinoCore-*.tar.bz2 ; do
-            aws s3 cp $f s3://${{ secrets.S3_BUCKET }}/
-          done
-
-  prepare-json:
-    name: Prepare jsons
-    runs-on: ubuntu-latest
-    needs:
-      - build-env
-      - package-core
-      - inspect-logs
-    env:
-      CORE_TAG: ${{ needs.build-env.outputs.CORE_TAG }}
-      CORE_HASH: ${{ needs.build-env.outputs.CORE_HASH }}
-      ARTIFACTS: ${{ needs.build-env.outputs.ARTIFACTS }}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          fetch-tags: true
-
-      - uses: actions/download-artifact@v4
-        with:
-          path: .
-          pattern: ArduinoCore-*
-          merge-multiple: true
-
-      - name: Prepare package index snippets
-        run: |
-          jq -cr '.[]' <<< ${ARTIFACTS} | while read -r artifact; do
-            ARTIFACT_FILE=ArduinoCore-${artifact}-${CORE_HASH}.tar.bz2
-            PACKAGE_JSON=ArduinoCore-${artifact}-${CORE_TAG}.json
-            ./extra/gen_package_index_json.sh ${artifact} ${ARTIFACT_FILE} ${PACKAGE_JSON}
-          done
-
-      - name: Archive package index snippets
-        uses: actions/upload-artifact@v4
-        with:
-          name: ArduinoCore-zephyr-${{ env.CORE_TAG }}-jsons
-          path: ArduinoCore-*-${{ env.CORE_TAG }}.json
+          exit ${{ ((needs.inspect-logs.outputs.CI_RESULT == 'PASSED') && !contains(needs.*.result, 'failure')) && '0' || '1' }}
