ci: refactor 3/7: process build logs with Python script
This commit replaces the previous shell script for log inspection
with a more comprehensive Python script processing.

The new script provides better organization of test results, including
a summary table, detailed per-artifact and per-skettch breakdowns,
and improved formatting for readability in GitHub Actions summaries.

Job database IDs are now obtained once before log generation instead of
once per job, solving API rate limit issues.

This also requires an update to compile-sketches to support two new
features:

- 'issues-report' generates an 'issues' array in the report with
  warning/error lines extracted from the compilation stderr;
- 'always-succeed' makes the action always exit 0, allowing CI to
  continue even when some compilations fail.

Signed-off-by: Luca Burelli <l.burelli@arduino.cc>

diff --git a/.github/workflows/package_core.yml b/.github/workflows/package_core.yml
--- a/.github/workflows/package_core.yml
+++ b/.github/workflows/package_core.yml
@@ -1,3 +1,8 @@
+# Copyright ARDUINO SRL (https://www.arduino.cc)
+# SPDX-License-Identifier: Apache-2.0
+
+# CI workflow to build, package, test and upload the ArduinoCore-zephyr core.
+
 name: Package, test and upload core
 
 on:
@@ -12,16 +17,32 @@ env:
 
 jobs:
 
+
+
+  # Prepare the Zephyr build environment once for all boards, to speed up the
+  # overall process and ensure all builds use the same environment and metadata.
+  # Several outputs are made available for later jobs to use.
+
   build-env:
     name: Prepare build environment
     runs-on: ubuntu-latest
     outputs:
+      # User-friendly SemVer-compatible version for the build. Matches the tag
+      # name if building a tagged commit, otherwise it is "slightly more" than
+      # the latest tag.
+      CORE_VER: ${{ env.CORE_VER }}
+      # Tag (if found) or hash identifying this core build, should be used for
+      # user-friendly strings and file names
       CORE_TAG: ${{ env.CORE_TAG }}
+      # Hash identifying this core build, should be used for exact version match
       CORE_HASH: ${{ env.CORE_HASH }}
+      # JSON describing all boards to build, collected by get_board_details.sh
       ALL_BOARD_DATA: ${{ env.ALL_BOARD_DATA }}
       ARTIFACTS: ${{ env.ARTIFACTS }}
+      # List of architectures the artifacts will be built for
       SUB_ARCHES: ${{ env.SUB_ARCHES }}
     steps:
+
       - name: Install OS dependencies
         working-directory: /opt
         run: |
@@ -34,24 +55,27 @@ jobs:
           submodules: 'recursive'
           fetch-depth: 0
           persist-credentials: false
-          fetch-tags: true
+          fetch-tags: true # needed for get_core_version.sh
 
       - name: Initialize Zephyr environment
         run: |
+          # Install Zephyr as a core user would, but faster
           yes | ./extra/bootstrap.sh -o=--filter=tree:0
           # Set up basic environment for later steps
           echo "CORE_HASH=$(git describe --always $HEAD_REF)" >> "$GITHUB_ENV"
           echo "ALL_BOARD_DATA=$(extra/get_board_details.sh | jq -c 'sort_by(.variant)')" >> "$GITHUB_ENV"
-          echo "## Building \`$(extra/get_core_version.sh)\`" >> "$GITHUB_STEP_SUMMARY"
+          echo "CORE_VER=$(extra/get_core_version.sh)" >> "$GITHUB_ENV"
 
       - name: Map output packages
-        # needs the above env vars to be usable
+        # needs the above env vars
         run: |
+          echo "## Building \`$CORE_VER\`" >> "$GITHUB_STEP_SUMMARY"
           echo "CORE_TAG=$(git describe --tags --exact-match 2>/dev/null || echo $CORE_HASH)" >> "$GITHUB_ENV"
           echo "ARTIFACTS=$(jq -c '["zephyr"] + (map(.artifact) | unique)' <<< ${ALL_BOARD_DATA})" >> "$GITHUB_ENV"
           echo "SUB_ARCHES=$(jq -c 'map(.subarch) | unique' <<< ${ALL_BOARD_DATA})" >> "$GITHUB_ENV"
-
+          # Archive the build environment for later jobs
           (cd && tar cphf - .cmake work zephyr-sdk-* | zstd > build-env.tar.zstd)
+          # The API is only needed for packaging, not for building, so it's separate
           tar cphf - cores/arduino/api | zstd > arduino-api.tar.zstd
 
       - name: Archive build environment
@@ -66,20 +90,32 @@ jobs:
           name: arduino-api
           path: arduino-api.tar.zstd
 
+
+
+  # Extract the build environment and compile the loader project for each board
+  # in parallel. The build logs and artifacts are intermediate results archived
+  # for later jobs.
+
   build-board:
-    name: Build loader for ${{ matrix.board }}
+    # NOTE: this name is hardcoded in ci_inspect_logs.py
+    name: Build for ${{ matrix.board }}
     runs-on: ubuntu-latest
     needs:
       - build-env
     env:
+      # ccache, don't look for the spec file anywhere
       CCACHE_IGNOREOPTIONS: -specs=*
-      OUTPUT_ARTIFACT: binaries-${{ matrix.board }}-${{ needs.build-env.outputs.CORE_HASH }}
+      # build-specific name of the generated artifacts
+      ARTIFACT_TAG: ${{ needs.build-env.outputs.CORE_HASH }}-${{ matrix.board }}
+      # report file stem for this board
+      REPORT: reports/zephyr-${{ matrix.variant }}
     strategy:
       matrix:
         include:
           ${{ fromJSON( needs.build-env.outputs.ALL_BOARD_DATA ) }}
       fail-fast: false
     steps:
+
       - uses: actions/download-artifact@v4
         with:
           path: /home/runner
@@ -101,30 +137,67 @@ jobs:
       - name: Build loader
         shell: bash
         run: |
-          if ! ./extra/build.sh ${{ matrix.board }} 2> >(tee error.log) ; then
+          # create the report directory
+          mkdir -p reports
+          # run the build, capturing stdout and stderr
+          if ! ./extra/build.sh ${{ matrix.board }} 1> >(tee $REPORT.stdout) 2> >(tee $REPORT.stderr) ; then
+            # build failed, capture errors in summary and stop job without artifacts
             echo "### :x: ${{ matrix.board }} (\`${{ matrix.variant }}\`) build errors" > $GITHUB_STEP_SUMMARY
             echo >> $GITHUB_STEP_SUMMARY
             echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            cat error.log >> $GITHUB_STEP_SUMMARY
+            cat $REPORT.stderr >> $GITHUB_STEP_SUMMARY
             echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
             exit 1
           fi
 
-      - name: Package board binaries
+          # look for warnings (errors are a happy path!)
+          grep -i "warning:" $REPORT.stdout > $REPORT.warnings || true
+
+          # extract the memory usage table (from the header to the first non-% line)
+          cat $REPORT.stdout | sed -n '/^Memory region/,/^[^%]*$/p' | head -n -1 \
+                             | awk 'BEGIN {split("B KB MB GB", u); for(i in u) m[u[i]]=1024^(i-1)} /:/ {print "[\"" $1 "\"," $2*m[$3] "," $4*m[$5] "]"}' \
+                             | sort | jq -s > $REPORT.meminfo
+
+      - name: Package board artifacts
         if: ${{ !cancelled() }}
         run: |
+          # add the config file to the report files, list them for later archiving
+          cp firmwares/zephyr-${{ matrix.variant }}.config $REPORT.config
+          echo "REPORT_FILES<<EOF" >> $GITHUB_ENV
+          ls reports/* >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+          # Preprare an archive of the built binaries (and build dir on failure)
+          [ "${{ job.status }}" == "failure" ] && FULL_BUILD_DIR="build/${{ matrix.variant }}/"
           tar chf - \
             firmwares/*${{ matrix.variant }}* \
             variants/${{ matrix.variant }}/ \
-            ${{ (job.status == 'failure') && format('build/{0}/', matrix.variant) }} \
-          | zstd > ${OUTPUT_ARTIFACT}.tar.zstd
+            ${FULL_BUILD_DIR} \
+          | zstd > binaries-${ARTIFACT_TAG}.tar.zstd
 
       - name: Archive board binaries
         if: ${{ !cancelled() }}
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ format('{0}{1}', (job.status == 'failure') && 'failed-' || '', env.OUTPUT_ARTIFACT) }}
-          path: ${{ env.OUTPUT_ARTIFACT }}.tar.zstd
+          # prefix the name with 'failed-' if the build failed, so that it is not removed
+          name: ${{ format('{0}binaries-{1}', (job.status == 'failure') && 'failed-' || '', env.ARTIFACT_TAG) }}
+          path: binaries-${{ env.ARTIFACT_TAG }}.tar.zstd
+          retention-days: 7 # for failed build inspection
+
+      - name: Archive build reports
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-report-${{ env.ARTIFACT_TAG }}
+          path: ${{ env.REPORT_FILES }}
+          retention-days: 1
+
+
+
+  # Compose the core packages for each architecture in parallel, by retrieving
+  # the API snapshot and the built binaries for all boards and packaging them.
+  # The resulting core packages are final artifacts, ready for publishing.
+  # The 'zephyr' umbrella package is also created here by including all others.
 
   package-core:
     name: Package ${{ matrix.artifact }}
@@ -142,6 +215,7 @@ jobs:
       fail-fast: false
     if: ${{ !cancelled() && needs.build-env.result == 'success' }}
     steps:
+
       - uses: actions/checkout@v4
         with:
           submodules: 'recursive'
@@ -149,11 +223,13 @@ jobs:
           persist-credentials: false
           fetch-tags: true
 
+      # Get the API snapshot
       - uses: actions/download-artifact@v4
         with:
           path: .
           name: arduino-api
 
+      # Get all built binaries
       - uses: actions/download-artifact@v4
         with:
           path: .
@@ -162,11 +238,13 @@ jobs:
 
       - name: Package core
         run: |
+          # Extract the API snapshot and board binaries in place
           rm -f cores/arduino/api # remove broken symlink
           tar --use-compress-program=unzstd -xpf arduino-api.tar.zstd
           for f in binaries-*.tar.zstd ; do
             tar --use-compress-program=unzstd -xpf $f
           done
+          # Create the core artifact for this set of boards
           ./extra/package_core.sh ${{ matrix.artifact }} ${CORE_TAG} distrib/${CORE_ARTIFACT}.tar.bz2
 
       - uses: actions/upload-artifact@v4
@@ -175,12 +253,18 @@ jobs:
           name: ${{ env.CORE_ARTIFACT }}
           path: distrib/${{ env.CORE_ARTIFACT }}.tar.bz2
 
+
+
+  # After generating the final cores, the API and per-board binary archives are no longer needed.
+  # The build environment archive can also be removed.
+
   cleanup-build:
     name: Clean up intermediates
     runs-on: ubuntu-latest
     needs:
       - package-core
     steps:
+
       - uses: geekyeggo/delete-artifact@v5.1.0
         with:
           name: |
@@ -189,8 +273,15 @@ jobs:
             build-env
           failOnError: false
 
+
+
+  # For each board and link mode, compile all test sketches using the just
+  # built core. The compilation reports are archived for later inspection.
+  # This step never fails, so that expected errors do not block the CI run.
+
   test-core:
-    name: Test ${{ matrix.subarch }}:${{ matrix.board }}
+    # NOTE: this name is hardcoded in ci_inspect_logs.py
+    name: Test ${{ matrix.board }}
     runs-on: ubuntu-latest
     needs:
       - build-env
@@ -232,7 +323,7 @@ jobs:
           extra/ci_test_list.sh ${{ matrix.artifact }} ${{ matrix.variant }}
 
       - name: Compile tests for ${{ matrix.board }}
-        uses: pillo79/compile-sketches@main
+        uses: pillo79/compile-sketches@4a1dead03155c17ddedc373699d7aa80a78a6c7d # next
         with:
           fqbn: ${{ env.FQBN }}
           platforms: |
@@ -252,106 +343,81 @@ jobs:
             - 'compiler.cpp.extra_flags=-Wno-type-limits -Wno-missing-field-initializers'
           verbose: 'false'
           enable-deltas-report: 'false'
-          enable-warnings-report: 'true'
-          enable-warnings-log: 'true'
-
-      - name: Get job ID
-        id: job_id
-        if: ${{ success() || failure() }}
-        uses: actions/github-script@main
-        with:
-          script: |
-            const { data: workflow_run } = await github.rest.actions.listJobsForWorkflowRun({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: context.runId
-            });
-            const job_name = `Test ${{ matrix.subarch }}:${{ matrix.board }}`
-            return workflow_run.jobs.find((job) => job.name === job_name).id;
+          enable-issues-report: 'true'
+          always-succeed: 'true'
 
       - name: Prepare log
         if: ${{ success() || failure() }}
         run: |
+          # make sure to create an empty report if none was created
+          [ ! -f sketches-reports/${REPORT_FILE} ] && mkdir -p sketches-reports && echo "{}" > sketches-reports/${REPORT_FILE}
+          # remove base path of the core install from all file references to make logs cleaner
           sed -i -e 's!/home/runner/.arduino15/packages/arduino/hardware/zephyr/[^/]*/!!g' sketches-reports/${REPORT_FILE}
-          cat sketches-reports/${REPORT_FILE} | jq -cr ".boards[0].sketches[0] += { job_id: ${{ steps.job_id.outputs.result }} }" > ${REPORT_FILE} && mv ${REPORT_FILE} sketches-reports/
 
+      # archive the compile report for later
       - uses: actions/upload-artifact@v4
         if: ${{ success() || failure() }}
         with:
           name: test-report-${{ env.ARTIFACT_TAG }}
           path: sketches-reports/*
 
-  collect-logs:
-    name: Collect logs
+
+
+  # Collect all build and test reports, analyze them and produce a summary.
+  # See ci_inspect_logs.py for details.
+
+  verify-core:
     runs-on: ubuntu-latest
     needs:
       - build-env
       - package-core
       - test-core
-    if: ${{ !cancelled() && needs.build-env.result == 'success' }}
+    if: ${{ !cancelled() }}
     env:
       ALL_BOARD_DATA: ${{ needs.build-env.outputs.ALL_BOARD_DATA }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      GH_REPO: ${{ github.repository }}
     steps:
+
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+          fetch-tags: true
+
       - uses: actions/download-artifact@v4
         with:
           path: .
-          pattern: test-report-*
+          pattern: "*-report-*"
           merge-multiple: true
 
       - run: |
-          ARTIFACTS=$(jq -cr 'map(.artifact) | unique | .[]' <<< ${ALL_BOARD_DATA}) # this avoids the 'zephyr' artifact
-          for artifact in $ARTIFACTS ; do
-            echo "### \`$artifact\` test results:" >> "$GITHUB_STEP_SUMMARY"
-            jq -c "map(select(.artifact == \"$artifact\")) | .[]" <<< ${ALL_BOARD_DATA} | while read -r BOARD_DATA; do
-              BOARD=$(echo $BOARD_DATA | jq -cr '.board')
-              VARIANT=$(echo $BOARD_DATA | jq -cr '.variant')
-              SUBARCH=$(echo $BOARD_DATA | jq -cr '.subarch')
-              FQBN="arduino:$SUBARCH:$BOARD"
-              REPORT_FILE="$(echo $FQBN | tr ':' '-').json"
-              if [ ! -f $REPORT_FILE ]; then
-                echo "* :x: $BOARD (\`$VARIANT\`) - No report found?" >> "$GITHUB_STEP_SUMMARY"
-              else
-                REPORT=$(jq -cr '.boards[0].sketches[0]' $REPORT_FILE)
-                JOB_ID=$(echo $REPORT | jq -cr '.job_id')
-                JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${JOB_ID}#step:5:2"
-                if ! $(echo $REPORT | jq -cr '.compilation_success') ; then
-                  echo "* :x: [$BOARD]($JOB_URL) (\`$VARIANT\`) - Build failed" >> "$GITHUB_STEP_SUMMARY"
-                else
-                  WARNINGS=$(echo $REPORT | jq -cr '.warnings.current.absolute // 0')
-                  if [ $WARNINGS -eq 0 ]; then
-                    echo "* :white_check_mark: $BOARD (\`$VARIANT\`) - Build successful" >> "$GITHUB_STEP_SUMMARY"
-                  else
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                    echo "<details><summary>&nbsp;&nbsp; :warning: <a href=\"$JOB_URL\">$BOARD</a> (<tt>$VARIANT</tt>) - $WARNINGS warnings:</summary>" >> "$GITHUB_STEP_SUMMARY"
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                    echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
-                    echo $REPORT | jq -cr '.warnings_log[]' >> "$GITHUB_STEP_SUMMARY"
-                    echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                    echo "</details>" >> "$GITHUB_STEP_SUMMARY"
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                  fi
-                fi
-              fi
-            done
-          done
+          # gather the array of job metadata (especially name and ID) for the current workflow run
+          export WORKFLOW_JOBS=$(gh run view ${{ github.run_id }} --attempt ${{ github.run_attempt }} --json jobs --jq '.jobs')
+          # Run the log inspection script
+          extra/ci_inspect_logs.py result summary full_log
+
+          # Display the summary and full log in the step summary
+          cat summary >> $GITHUB_STEP_SUMMARY
+          cat full_log >> $GITHUB_STEP_SUMMARY
 
       - name: Clean up intermediate artifacts
         uses: geekyeggo/delete-artifact@v5.1.0
         with:
-          name: test-report-*
+          name: |
+            build-report-*
+            test-report-*
           failOnError: false
 
-  verify-core:
-    runs-on: ubuntu-latest
-    if: cancelled() || contains(needs.*.result, 'failure')
-    needs:
-      - build-env
-      - package-core
-      - test-core
-    steps:
-      - name: Notify failure
-        run: exit 1
+      # The last line makes the job fail if the 'result' file does not contain "PASSED".
+      # No further actions are allowed in case of error.
+      - run: |
+          cat result
+          grep "PASSED" result >& /dev/null # otherwise CI test failed
+
+
+
+  # Upload the built core packages to the S3 bucket for public distribution.
 
   publish-core:
     name: Publish core
@@ -360,12 +426,13 @@ jobs:
     needs:
       - build-env
       - package-core
-      - test-core
+      - verify-core
     environment: production
     permissions:
       id-token: write
       contents: read
     steps:
+
       - uses: actions/download-artifact@v4
         with:
           path: .
@@ -384,18 +451,21 @@ jobs:
             aws s3 cp $f s3://${{ secrets.S3_BUCKET }}/
           done
 
+  # Prepare the package index JSON snippets for the newly built core packages.
+
   prepare-json:
     name: Prepare jsons
     runs-on: ubuntu-latest
     needs:
       - build-env
       - package-core
-      - test-core
+      - verify-core
     env:
       CORE_TAG: ${{ needs.build-env.outputs.CORE_TAG }}
       CORE_HASH: ${{ needs.build-env.outputs.CORE_HASH }}
       ARTIFACTS: ${{ needs.build-env.outputs.ARTIFACTS }}
     steps:
+
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
@@ -411,6 +481,8 @@ jobs:
       - name: Prepare package index snippets
         run: |
           jq -cr '.[]' <<< ${ARTIFACTS} | while read -r artifact; do
+            # note: the archive names are always hash-based so they use a
+            # predictable pattern. JSON files can use the tag for user-friendliness.
             ARTIFACT_FILE=ArduinoCore-${artifact}-${CORE_HASH}.tar.bz2
             PACKAGE_JSON=ArduinoCore-${artifact}-${CORE_TAG}.json
             ./extra/gen_package_index_json.sh ${artifact} ${ARTIFACT_FILE} ${PACKAGE_JSON}
