ci: package_core: ignore failure of ci_calc_size_reports.py
It is possible that a race condition between pull requests and pushes
causes ci_calc_size_reports.py to fail when size information for the
base commit of a pull request is not available in AWS.

This only affects the generation of size reports, which is just a
nice-to-have but not critical part of the CI process. A failure will
still trigger a warning by upload-artifact later, when it detects the
artifact is missing.

diff --git a/.github/workflows/package_core.yml b/.github/workflows/package_core.yml
--- a/.github/workflows/package_core.yml
+++ b/.github/workflows/package_core.yml
@@ -441,7 +441,8 @@ jobs:
         if: ${{ github.event_name == 'pull_request' }}
         run: |
           export GITHUB_BASE_SHA=$(git describe --always origin/${GITHUB_BASE_REF})
-          extra/ci_calc_size_reports.py ${GITHUB_BASE_SHA} sketches-reports/
+          # errors due to race conditions with parallel branch runs should not fail the job
+          extra/ci_calc_size_reports.py ${GITHUB_BASE_SHA} sketches-reports/ || true
 
       # upload comment request artifact (will be retrieved by leave_pr_comment.yml)
       - name: Archive comment information
