wip

diff --git a/.github/workflows/package_core.yml b/.github/workflows/package_core.yml
--- a/.github/workflows/package_core.yml
+++ b/.github/workflows/package_core.yml
@@ -114,17 +114,38 @@ jobs:
             exit 1
           fi
 
-          cp output.log firmwares/zephyr-${{ matrix.variant }}.stderr
-          cp error.log firmwares/zephyr-${{ matrix.variant }}.stderr
+          # look for warnings (errors are a happy path!)
+          grep -i "warning:" output.log > firmwares/zephyr-${{ matrix.variant }}.warnings || true
 
           # extract the memory usage table (from the header to the first non-% line)
           cat output.log | sed -n '/^Memory region/,/^[^%]*$/p' | head -n -1 \
                          | awk 'BEGIN {split("B KB MB GB", u); for(i in u) m[u[i]]=1024^(i-1)} /:/ {print "[\"" $1 "\"," $2*m[$3] "," $4*m[$5] "]"}' \
                          | sort | jq -s > firmwares/zephyr-${{ matrix.variant }}.meminfo
 
-      - name: Package board binaries
+      - name: Get build job ID
+        id: job_id
+        if: ${{ success() || failure() }}
+        uses: actions/github-script@main
+        with:
+          script: |
+            const { data: workflow_run } = await github.rest.actions.listJobsForWorkflowRun({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              run_id: context.runId
+            });
+            const job_name = `Build loader for ${{ matrix.board }}`
+            return workflow_run.jobs.find((job) => job.name === job_name).id;
+
+      - name: Package board artifacts
         if: ${{ !cancelled() }}
         run: |
+          # Archive job ID, warnings and memory info as 'report' artifact
+          echo ${{ steps.job_id.outputs.result }} > firmwares/zephyr-${{ matrix.variant }}.jobid
+          tar chf - \
+            firmwares/zephyr-${{ matrix.variant }}.{jobid,warnings,meminfo} \
+          | zstd > build-report-${ARTIFACT_TAG}.tar.zstd
+          rm firmwares/zephyr-${{ matrix.variant }}.{jobid,warnings,meminfo}
+          # Archive built binaries (and build dir on failure)
           tar chf - \
             firmwares/*${{ matrix.variant }}* \
             variants/${{ matrix.variant }}/ \
@@ -142,10 +163,8 @@ jobs:
         if: ${{ !cancelled() }}
         uses: actions/upload-artifact@v4
         with:
-          name: mem-report-${{ env.ARTIFACT_TAG }}
-          path: |
-            firmwares/zephyr-${{ matrix.variant }}.meminfo
-            firmwares/zephyr-${{ matrix.variant }}.config
+          name: build-report-${{ env.ARTIFACT_TAG }}
+          path: build-report-${{ env.ARTIFACT_TAG }}.tar.zstd
 
   package-core:
     name: Package ${{ matrix.artifact }}
@@ -273,7 +292,7 @@ jobs:
           enable-issues-report: 'true'
           always-succeed: 'true'
 
-      - name: Get job ID
+      - name: Get test job ID
         id: job_id
         if: ${{ success() || failure() }}
         uses: actions/github-script@main
@@ -343,7 +362,7 @@ jobs:
         uses: geekyeggo/delete-artifact@v5.1.0
         with:
           name: |
-            mem-report-*
+            build-report-*
             test-report-*
           failOnError: false
 
