package_core: refact 2/x: process logs with Python script
This commit replaces the previous shell script for log inspection
with a more comprehensive processing with Python script.

The new script provides better organization of test results, including
a summary table, detailed per-artifact and per-sketch breakdowns,
and improved formatting for readability in GitHub Actions summaries.

Job database IDs are now obtained once before log generation instead of
once per job, solving API rate limit issues.

This also requires an update to compile-sketches for 2 new features:
- 'issues-report' generates an 'issues' array in the report with
  warning/error lines extracted from the compilation stderr;
- 'always-succeed' makes the action always exit 0, allowing
  CI to continue even when some compilations fail.

Signed-off-by: Luca Burelli <l.burelli@arduino.cc>

diff --git a/.github/workflows/package_core.yml b/.github/workflows/package_core.yml
--- a/.github/workflows/package_core.yml
+++ b/.github/workflows/package_core.yml
@@ -65,13 +65,15 @@ jobs:
           path: arduino-api.tar.zstd
 
   build-board:
-    name: Build loader for ${{ matrix.board }}
+    # NOTE: this name is hardcoded in ci_inspect_logs.py
+    name: Build for ${{ matrix.board }}
     runs-on: ubuntu-latest
     needs:
       - build-env
     env:
       CCACHE_IGNOREOPTIONS: -specs=*
-      OUTPUT_ARTIFACT: binaries-${{ matrix.board }}-${{ needs.build-env.outputs.CORE_HASH }}
+      ARTIFACT_TAG: ${{ needs.build-env.outputs.CORE_HASH }}-${{ matrix.board }}
+      REPORT: reports/zephyr-${{ matrix.variant }}
     strategy:
       matrix:
         include:
@@ -99,30 +101,53 @@ jobs:
       - name: Build loader
         shell: bash
         run: |
-          if ! ./extra/build.sh ${{ matrix.board }} 2> >(tee error.log) ; then
+          mkdir -p reports
+          if ! ./extra/build.sh ${{ matrix.board }} 1> >(tee $REPORT.stdout) 2> >(tee $REPORT.stderr) ; then
             echo "### :x: ${{ matrix.board }} (\`${{ matrix.variant }}\`) build errors" > $GITHUB_STEP_SUMMARY
             echo >> $GITHUB_STEP_SUMMARY
             echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            cat error.log >> $GITHUB_STEP_SUMMARY
+            cat $REPORT.stderr >> $GITHUB_STEP_SUMMARY
             echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
             exit 1
           fi
 
-      - name: Package board binaries
+          # look for warnings (errors are a happy path!)
+          grep -i "warning:" $REPORT.stdout > $REPORT.warnings || true
+
+          # extract the memory usage table (from the header to the first non-% line)
+          cat $REPORT.stdout | sed -n '/^Memory region/,/^[^%]*$/p' | head -n -1 \
+                             | awk 'BEGIN {split("B KB MB GB", u); for(i in u) m[u[i]]=1024^(i-1)} /:/ {print "[\"" $1 "\"," $2*m[$3] "," $4*m[$5] "]"}' \
+                             | sort | jq -s > $REPORT.meminfo
+
+      - name: Package board artifacts
         if: ${{ !cancelled() }}
         run: |
+          cp firmwares/zephyr-${{ matrix.variant }}.config $REPORT.config
+          echo "REPORT_FILES<<EOF" >> $GITHUB_ENV
+          ls reports/* >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+          # Archive built binaries (and build dir on failure)
+          [ "${{ job.status }}" == "failure" ] && FULL_BUILD_DIR="build/${{ matrix.variant }}/"
           tar chf - \
             firmwares/*${{ matrix.variant }}* \
             variants/${{ matrix.variant }}/ \
-            ${{ (job.status == 'failure') && format('build/{0}/', matrix.variant) }} \
-          | zstd > ${OUTPUT_ARTIFACT}.tar.zstd
+            ${FULL_BUILD_DIR} \
+          | zstd > binaries-${ARTIFACT_TAG}.tar.zstd
 
       - name: Archive board binaries
         if: ${{ !cancelled() }}
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ format('{0}{1}', (job.status == 'failure') && 'failed-' || '', env.OUTPUT_ARTIFACT) }}
-          path: ${{ env.OUTPUT_ARTIFACT }}.tar.zstd
+          name: ${{ format('{0}binaries-{1}', (job.status == 'failure') && 'failed-' || '', env.ARTIFACT_TAG) }}
+          path: binaries-${{ env.ARTIFACT_TAG }}.tar.zstd
+
+      - name: Archive build reports
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-report-${{ env.ARTIFACT_TAG }}
+          path: ${{ env.REPORT_FILES }}
 
   package-core:
     name: Package ${{ matrix.artifact }}
@@ -195,7 +220,8 @@ jobs:
           failOnError: false
 
   test-core:
-    name: Test ${{ matrix.subarch }}:${{ matrix.board }}
+    # NOTE: this name is hardcoded in ci_inspect_logs.py
+    name: Test ${{ matrix.board }}
     runs-on: ubuntu-latest
     needs:
       - build-env
@@ -235,7 +261,7 @@ jobs:
           extra/ci_test_list.sh ${{ matrix.artifact }} ${{ matrix.variant }}
 
       - name: Compile tests for ${{ matrix.board }}
-        uses: pillo79/compile-sketches@main
+        uses: pillo79/compile-sketches@4a1dead03155c17ddedc373699d7aa80a78a6c7d # next
         with:
           fqbn: ${{ env.FQBN }}
           platforms: |
@@ -254,28 +280,14 @@ jobs:
             - 'compiler.cpp.extra_flags=-Wno-type-limits -Wno-missing-field-initializers'
           verbose: 'false'
           enable-deltas-report: 'false'
-          enable-warnings-report: 'true'
-          enable-warnings-log: 'true'
-
-      - name: Get job ID
-        id: job_id
-        if: ${{ success() || failure() }}
-        uses: actions/github-script@main
-        with:
-          script: |
-            const { data: workflow_run } = await github.rest.actions.listJobsForWorkflowRun({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              run_id: context.runId
-            });
-            const job_name = `Test ${{ matrix.subarch }}:${{ matrix.board }}`
-            return workflow_run.jobs.find((job) => job.name === job_name).id;
+          enable-issues-report: 'true'
+          always-succeed: 'true'
 
       - name: Prepare log
         if: ${{ success() || failure() }}
         run: |
+          [ ! -f sketches-reports/${REPORT_FILE} ] && mkdir -p sketches-reports && echo "{}" > sketches-reports/${REPORT_FILE}
           sed -i -e 's!/home/runner/.arduino15/packages/arduino/hardware/zephyr/[^/]*/!!g' sketches-reports/${REPORT_FILE}
-          cat sketches-reports/${REPORT_FILE} | jq -cr ".boards[0].sketches[0] += { job_id: ${{ steps.job_id.outputs.result }} }" > ${REPORT_FILE} && mv ${REPORT_FILE} sketches-reports/
 
       - uses: actions/upload-artifact@v4
         if: ${{ success() || failure() }}
@@ -283,8 +295,8 @@ jobs:
           name: test-report-${{ env.ARTIFACT_TAG }}
           path: sketches-reports/*
 
-  collect-logs:
-    name: Collect logs
+  inspect-logs:
+    name: Analyze logs
     runs-on: ubuntu-latest
     needs:
       - build-env
@@ -293,67 +305,50 @@ jobs:
     if: ${{ !cancelled() && needs.build-env.result == 'success' }}
     env:
       ALL_BOARD_DATA: ${{ needs.build-env.outputs.ALL_BOARD_DATA }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      GH_REPO: ${{ github.repository }}
     steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+          fetch-tags: true
+
       - uses: actions/download-artifact@v4
         with:
           path: .
-          pattern: test-report-*
+          pattern: "*-report-*"
           merge-multiple: true
 
       - run: |
-          ARTIFACTS=$(jq -cr 'map(.artifact) | unique | .[]' <<< ${ALL_BOARD_DATA}) # this avoids the 'zephyr' artifact
-          for artifact in $ARTIFACTS ; do
-            echo "### \`$artifact\` test results:" >> "$GITHUB_STEP_SUMMARY"
-            jq -c "map(select(.artifact == \"$artifact\")) | .[]" <<< ${ALL_BOARD_DATA} | while read -r BOARD_DATA; do
-              BOARD=$(echo $BOARD_DATA | jq -cr '.board')
-              VARIANT=$(echo $BOARD_DATA | jq -cr '.variant')
-              SUBARCH=$(echo $BOARD_DATA | jq -cr '.subarch')
-              FQBN="arduino:$SUBARCH:$BOARD"
-              REPORT_FILE="$(echo $FQBN | tr ':' '-').json"
-              if [ ! -f $REPORT_FILE ]; then
-                echo "* :x: $BOARD (\`$VARIANT\`) - No report found?" >> "$GITHUB_STEP_SUMMARY"
-              else
-                REPORT=$(jq -cr '.boards[0].sketches[0]' $REPORT_FILE)
-                JOB_ID=$(echo $REPORT | jq -cr '.job_id')
-                JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${JOB_ID}#step:5:2"
-                if ! $(echo $REPORT | jq -cr '.compilation_success') ; then
-                  echo "* :x: [$BOARD]($JOB_URL) (\`$VARIANT\`) - Build failed" >> "$GITHUB_STEP_SUMMARY"
-                else
-                  WARNINGS=$(echo $REPORT | jq -cr '.warnings.current.absolute // 0')
-                  if [ $WARNINGS -eq 0 ]; then
-                    echo "* :white_check_mark: $BOARD (\`$VARIANT\`) - Build successful" >> "$GITHUB_STEP_SUMMARY"
-                  else
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                    echo "<details><summary>&nbsp;&nbsp; :warning: <a href=\"$JOB_URL\">$BOARD</a> (<tt>$VARIANT</tt>) - $WARNINGS warnings:</summary>" >> "$GITHUB_STEP_SUMMARY"
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                    echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
-                    echo $REPORT | jq -cr '.warnings_log[]' >> "$GITHUB_STEP_SUMMARY"
-                    echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                    echo "</details>" >> "$GITHUB_STEP_SUMMARY"
-                    echo >> "$GITHUB_STEP_SUMMARY"
-                  fi
-                fi
-              fi
-            done
-          done
+          export WORKFLOW_JOBS=$(gh run view ${{ github.run_id }} --attempt ${{ github.run_attempt }} --json jobs --jq '.jobs')
+          extra/ci_inspect_logs.py result summary full_log
+
+          cat summary >> $GITHUB_STEP_SUMMARY
+          cat full_log >> $GITHUB_STEP_SUMMARY
 
       - name: Clean up intermediate artifacts
         uses: geekyeggo/delete-artifact@v5.1.0
         with:
-          name: test-report-*
+          name: |
+            build-report-*
+            test-report-*
           failOnError: false
+
+      - run: |
+          [ $(cat result) == 'PASSED' ] # otherwise CI test failed
 
   verify-core:
     runs-on: ubuntu-latest
-    if: cancelled() || contains(needs.*.result, 'failure')
     needs:
       - build-env
       - package-core
-      - test-core
+      - inspect-logs
+    if: ${{ !cancelled() }}
     steps:
-      - name: Notify failure
-        run: exit 1
+      - name: CI run result
+        run: |
+          exit ${{ contains(needs.*.result, 'failure') && '1' || '0' }}
 
   publish-core:
     name: Publish core
@@ -362,7 +357,7 @@ jobs:
     needs:
       - build-env
       - package-core
-      - test-core
+      - inspect-logs
     environment: production
     permissions:
       id-token: write
@@ -392,7 +387,7 @@ jobs:
     needs:
       - build-env
       - package-core
-      - test-core
+      - inspect-logs
     env:
       CORE_TAG: ${{ needs.build-env.outputs.CORE_TAG }}
       CORE_HASH: ${{ needs.build-env.outputs.CORE_HASH }}
